"""PR Builder - creates GitHub PRs with Henchmen labeling."""

import logging
from typing import Any

logger = logging.getLogger(__name__)

_HENCHMEN_LABEL = "henchmen-operative"


class PRBuilder:
    """Creates GitHub PRs with Henchmen labeling."""

    def __init__(self, settings: Any) -> None:
        self.settings = settings

    async def create_pr(
        self,
        repo: str,
        head_branch: str,
        base_branch: str,
        title: str,
        body: str,
        task_id: str,
    ) -> dict[str, Any]:
        """Create a GitHub PR with henchmen-operative label."""
        from github import Github

        g = Github(self._get_token())
        github_repo = g.get_repo(repo)

        pr = github_repo.create_pull(
            title=title,
            body=self._build_body(body, task_id),
            head=head_branch,
            base=base_branch,
        )

        # Add label
        pr.add_to_labels(_HENCHMEN_LABEL)

        return {
            "pr_url": pr.html_url,
            "pr_number": pr.number,
            "title": pr.title,
        }

    def _build_body(self, body: str, task_id: str) -> str:
        """Build PR body with Henchmen metadata."""
        return f"{body}\n\n---\n🤖 Generated by Henchmen Agent Factory\nTask ID: {task_id}"

    def _get_token(self) -> str:
        """Retrieve the GitHub token from settings or Secret Manager."""
        # In production this resolves via Secret Manager; for now fall back to a
        # settings attribute that tests / local dev can populate.
        return getattr(self.settings, "github_token", "") or ""
